version: '2'
services:
  web:
    container_name: guide
    labels:
      - jekyll
    env_file:
      - ./environment/dev.env
    image: jekyll/jekyll:3.1.6
    volumes:
      - ./guide:/srv/jekyll
    ports:
      - "4000:4000"
    command: jekyll serve --host=0.0.0.0 --watch --force_polling
